<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Plugin\DMC5DualSense.cs" Link="DMC5DualSense.cs" />
    <Reference Include="REFramework.NET">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Devil May Cry 5\reframework\plugins\REFramework.NET.dll</HintPath>
    </Reference>
    <Reference Include="REFramework.NET._mscorlib">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Devil May Cry 5\reframework\plugins\managed\generated\REFramework.NET._mscorlib.dll</HintPath>
    </Reference>
    <Reference Include="REFramework.NET.viacore">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Devil May Cry 5\reframework\plugins\managed\generated\REFramework.NET.viacore.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
